data:
  review_path: data/AmazonReviews/en_de_kitchen_test.json # reviews
indexer:
  host: localhost
  port: 9200
  username: elastic
  password: "" # or password in case you have changed a password to access elasticsearch instance
  index: amazon_reviews
  language: english


